echo "*****************************************************************"
echo "*    pdwfs Example: HydroC Simulation + ParaView + FFmpeg       *"
echo "*                                                               *"
echo "* To execute the workflow using \"normal\" files on disk:         *"
echo "* $ ./run_on_disk.sh                                            *"
echo "*                                                               *"
echo "* To execute the same workflow through pdwfs:                   *"
echo "* $ ./run_on_pdwfs.sh                                           *"
echo "*****************************************************************"
