echo "*************************************************************"
echo "*        Welcome to pdwfs development container             *"
echo "*                                                           *"
echo "* To build pdwfs:                                           *"
echo "* $ make                                                    *"
echo "*                                                           *"  
echo "* To run the test suite:                                    *"
echo "* $ make test                                               *"
echo "*************************************************************"
