echo "*************************************************************"
echo "*        Welcome to pdwfs development container             *"
echo "*                                                           *"
echo "* To run the test suite you need a running Redis instance:  *"
echo "*                                                           *"  
echo "* $ scripts/pdwfs-redis start                               *"
echo "* $ make test                                               *"
echo "*************************************************************"
