echo "*****************************************************************"
echo "*                pdwfs Example: IOR benchmark                   *"
echo "*                                                               *"
echo "* Start a jupyter-notebook server in this container:            *"
echo "* $ jupyter-notebook                                            *"
echo "*                                                               *"
echo "* then on your host, go to http://localhost:8888                *"
echo "* and open the notebook: ior_example.ipynb                      *"
echo "*                                                               *"
echo "* if you need to save your modifications, copy the files in     *"
echo "* the folder /notebook (it's a mounted volume to the host)      *"
echo "*****************************************************************"
