#!/bin/bash

usage="Usage: $(basename "$0") [-h] [command] 

Helper script to start a redis instance for testing purposes

where [command] must be either:
    start   start a redis instance listening on localhost and default port (6379)
    stop    stop the running redis instance
    restart restart the running redis instance
    cli     open redis CLI"


stop_redis() {
    redis-cli shutdown
}

start_redis() {
    redis-server --daemonize yes --save ""
}

while [ -n "$1" ]; do
    case "$1" in
    -h)     
        echo "$usage"
        exit 0
        ;;
    stop)   
        stop_redis
        exit 0
        ;;
    start)      
        start_redis    
        exit 0
        ;;
    restart)    
        stop_redis
        start_redis
        exit 0
        ;;
    cli)
        redis-cli
        exit 0
        ;;
    *) 
        echo "Error: Command $1 not recognized"
        echo "$usage"
        exit 1
        ;;
    esac
done

echo "$usage"
exit 1


